FROM golang:1.12-alpine as builder


RUN apk add --update --no-cache curl bash python \
  && curl https://sdk.cloud.google.com | bash
  
ENV PATH $PATH:/root/google-cloud-sdk/bin

WORKDIR /go/src/go-clean-arch
COPY . .
